### ISSUE TITLE
CLI Support

### ISSUE THREAD

**Issue by chrisdudley** [alexdesignworks/site_test#5]
Thanks for site_test - very useful.
Have you had any luck invoking site_test tests via the CLI (scripts/run-tests.sh) ?

**Comment by alexdesignworks** [comment]
@chrisdudley
`site_test` tests are normal tests, so they are invoked in the same way as all other tests.
There is no command to invoke only all site_test tests as `scripts/run-tests.sh` does not differentiate between normal and site_test tests.

**Comment by chrisdudley** [comment]
Thanks for the confirmation. I think i've found the issue - we're using aegir and so local settings.php doesn't have the database information in it, it's injected into the PHP process by nginx. But that means run-tests can't find the values. I'll hack run-tests to parse the nginx config file first and see how I get on.
